### ISSUE TITLE
Namespace as module name

### ISSUE THREAD

**Issue by mikolus** [frhagn/Typewriter#140]
Is there any way to have modules named after namespaces? To have something like:

```
export module $Namespace
{
    $Classes(*VM)[
    export class $Name {
        $Properties[
        // $LoudName
        public $name: $Type = $Type[$Default];]
    }]
}
```

I need it to be able to import multiple typings to my Angular2 component. Unless there is a better way to do it?

**Comment by aluanhaddad** [comment]
That is how they work by default. But these are "internal modules", not namespaces and you should use the `namespace` keyword instead of the `module` keyword to avoid confusion. If you are trying to generate "external modules", that is ES Modules, I have a good setup.

**Comment by frhagn** [comment]
`$Namespace` is a property on `$Class`, so you can try to include the namespace in the classes template like this:

```
$Classes(*VM)[
export module $Namespace {
    export class $Name {
        $Properties[
        public $name: $Type = $Type[$Default];]
    }
}]
```

**Comment by gregveres** [comment]
Good suggestion @frhagn. I was coming here to start a discussion about some sort of higher level abstraction as input to typewriter because I am finding myself making many copies of the same .tst file and changing two things:
namespace <namespace_path> 
and 
$Classes(<c# class path>)

I think by moving the namespace inside the $Classes[] structure, I can eliminate this as one need for multiple files. However, I am doing a mapping so I might have to put this into a function that takes the $Namespace and returns the module name I want. 

**I can have multiple lists in the $Classes? If so what would the syntax be?** 

I was also putting these files into their own directories with the other TS files that support that function and I think that typewriter requires separate tst files for that. 

But I can see having a structure like this:
src/services/Services.tst
src/services/ViewModels.tst

this would put all the back end related auto generated files together. I can wrap my head around that structure. 

I really love typewriter. Its a great tool!

**Comment by gregveres** [comment]
Sorry I realize I am hijacking this thread. I am going to start a new thread for my question about multiple filters in $Classes.

**Comment by gregveres** [comment]
Never mind. I just saw the answer to Issue #95. in that answer you show how to use the lambda expressions to do exactly what I was looking for. Also @wonkim00 shows how to build a custom attribute and use that as a selection mechanism. 

I think the end result will be that I will use the base class selector for my API controllers in one .tst file and I will use the custom attribute for my view models in another .tst file. 

Greg

**Comment by gregveres** [comment]
@aluanhaddad I just re-read what you posted and noticed that you said you have a good setup. Would you mind sharing? 

I am in the process of converting all my namespace based definitions to external modules. I am in the process of adopting requireJS to load all my code. I would love to see what others are doing. 

If you would like to share, you can either post here or email me at greg.veres @ rogers dot com.

Thanks
Greg

**Comment by aluanhaddad** [comment]
@gregveres Sorry for the delay. Honestly my feelings about my setup have taken a downturn. Also, they may not be sufficient for your use cases. My use cases are rather simple, I am primarily generating types, not values.
Here is how I generate interfaces from server side model classes:
```php
$Classes($IncludeClass)[$Imports[import $ImportTypeName from '$FileName';
]$HasImports[
]$DocComment[/**
  * $Summary
  */
]interface $Name $HasExtends[extends ]$TypesExtended[$Name][, ]$HasExtends[ ]{
$Properties[
  $DocComment[/**
    * $Summary
    */
  ]$HasSetter[][readonly ]$name: $Type[$IsDate[Moment][$Name]];
]
}

export default $Name;]
```
Sorry for the poor readability, whitespace generation is a major pain.
Anyway, on build of the containing .csproj, I have a powershell script that enumerates the director to generate an index and re-exports everything, but this is just a convenience because in the same script I copy the directory to the client side project.

**Comment by RudeySH** [comment]
@aluanhaddad Am I missing something here or did you leave out a lot of code from your setup? Where do `$Imports`, `$ImportTypeName`, `$FileName`, `$HasImports` , `$HasExtends` and `$TypesExtended` come from?

**Comment by gregveres** [comment]
@RudeySH are you looking for something in particular? Its been a while since this thread and I feel I have a pretty good setup at this point that I am willing to share, I just haven't found the time to clean it up and write documentation.

**Comment by RudeySH** [comment]
@gregveres I'm looking for a .tst file that puts the generated interfaces in separate modules, similar to their C# namespaces. The interfaces could potentially have property types that come from other modules, so it needs to generate imports too. It should also be possible for an interface to extend another interface that comes from a different module.

**Comment by gregveres** [comment]
Ok. Do you really need that? Do interfaces need to go into separate namespaces? They don't generate any real code, just a definition that is referenced. 

I put all of my interfaces into a single namespace called SkyCourtAPI (my thought there was that it was all part of the definition of the API to interact with the server.). Also, since these are just interfaces, there is no import that is needed. I just reference them with their namespace qualified name. So even if you do want to separate your interfaces into separate namespaces, you don't need the complications of imports. Imports are a pain in the butt to infer. I ended up creating an attribute that indicates where the class should be imported from.

I am using Knockout so I do generate Knockout versions of my interfaces. These are real classes, not just interfaces because they create the code that creates a set of knockout observable variables from the C# member fields. In this case, I do have some C# inheritance going on that translates into typescript inheritance of my knockout classes. This is where the import attribute comes in. 

I am also using attributes to control which C# structures are being exported. I have [ExportToTypescript] to generate an interface and [ExportToTypescriptWithKnockout] to generate the knockout class. 

if you email me greg . veres at rogers dot com, I will send you my tst files. and we can have a conversation about how to use them.
