### ISSUE TITLE
Version 1.13 not available for download?

### ISSUE THREAD

**Issue by mailivore** [frhagn/Typewriter#216]
Hi,

I would like to update to 1.13 to fix my asp.net core routing.
It seems that you released this version one month ago but only 1.12.2 is available for download.

Where can I find the last version?

Thanks

**Comment by frhagn** [comment]
Hi @mailivore,
unfortunately I haven't been able to publish the new version (1.13.0) to the Visual Studio Gallery due to an error in the gallery.. Microsoft has been investigating the issue for a month now so hopefully the issue will be resolved soon.. Meanwhile you can download it from https://github.com/frhagn/Typewriter/releases

You can follow the issue here: https://developercommunity.visualstudio.com/content/problem/99725/cannot-upload-vsix-to-visual-studio-gallery.html 
cc @madskristensen

**Comment by mailivore** [comment]
Thanks, I was not able to find the release page by myself.

The update solved my problem, thanks for this amazing plugin!

**Comment by frhagn** [comment]
The publishing issue is resolved so the new version is available in the marketplace now.
