### ISSUE TITLE
Debugging templates

### ISSUE THREAD

**Issue by cwoolum** [frhagn/Typewriter#58]
Hey All,

I was wondering how to debug these templates? I'm writing some custom extension methods and i'm not getting a lot of feedback on why the code is not generating. 

Thanks!

**Comment by johannordin** [comment]
Hey @cwoolum! There is a special output for typewriter that you can use (in the output window select "typewriter" instead of "build" or whatever was previously selected), it usualy gives you some good hints about whats wrong. Good enough? You can also use try-catch in your extension and output the exception to your generated files. 
Good luck!

**Comment by cwoolum** [comment]
Thanks Johan! I was getting vague error messages but I'll definitely check out the try/catch.

**Comment by frhagn** [comment]
I'm not sure if it's possible to implement debugging, but it would definetly be a nice feature. I'll look into that.
