### ISSUE TITLE
Utilize an existing templating engine vs. a new custom one

### ISSUE THREAD

**Issue by OniBait** [frhagn/Typewriter#68]
Would be extremely nice to be able to leverage one of the existing templating engines that are out there for .NET instead of the custom new one you have. By utilizing something like the RazorEngine (https://github.com/Antaris/RazorEngine), it would add a lot of flexibility to what one could do with the templates.

**Comment by frhagn** [comment]
Hi @OniBait. Most template engines (that I'm aware of) including Razor isn't really suited to generate C-like output such as TypeScript. It's hard to differentiate the C# statements from the TypeScript ones. This is why I choose to use a custom template syntax. 

I'm thinking about adding the possibility to load external references from Typewriter templates. If/when that functionality is implemented it would be possible to import a templateing engine and use that instead of the built in engine.
