### ISSUE TITLE
OutputFilenameFactory no longer supports changing path

### ISSUE THREAD

**Issue by hamtamtots** [frhagn/Typewriter#80]
We were using TypeWriter in this fashion:

    settings.OutputFilenameFactory = file => {
            return $"generatedHubs/{hubClass}.ts";
        };

Which worked quite well in new xproj projects, as the project files now reflect the filesystem, therefore the new files were being added to the specified path.

There has been a recent change to replace "invalid" characters ('/' to '-') which has broken our current use cases. I realise there has been mention of not supporting creating files outside of a project, but is there any scope to allow setting the path name of a file. I'm sure it would be a useful feature as it prevents a lot of code redundancy if generating ts files in different locations.

**Comment by frhagn** [comment]
Hi @hamtamtots,
Saving the output files in other folders can result in some unstable behaviour. There's been some issues where people using this approach have experienced lost files and folders (see #71). This is why I made the change to replace the "invalid" characters.

I'm looking at adding support for xproj and some more flexibility for the file management, but for now it's not suported.

Anyway, if this approach is working for you I can restore the possibility in the next update.
Meanwhile you can download the previous version under [releases](https://github.com/frhagn/Typewriter/releases)

**Comment by LeeCheneler** [comment]
Instead of replacing the invalid characters with a '-' could you not just throw an exception? Then we can respond to the exception and fix our naming or whatever needs to be done.

I don't see '\\' and '/' being invalid, I think being able to change the output directory is vital if this tool is to realize it full potential. Keeping all generations under the .tst file will make it awkward when building a larger app where you are organizing your typescript with a certain folder structure. Being able to map the generated files to different locations helps keep the project organised. 

The behavior could be achieved with a .tst file in every space you want to generate files to, but why have 2, 5, 10, 100+ .tst files when you could achieve it one well written one? And that is totally achievable, we've done it with 1 file and its spewing out loads of models for us in different directories, by just allowing the output path to be changed.

**Comment by frhagn** [comment]
Issue resolved in 1.3.1 by removing the replace for '/' and '\'. Still not "officially" supported though
