### ISSUE TITLE
How do you use this template? 

### ISSUE THREAD

**Issue by FreeFrags** [frhagn/Typewriter#85]
https://github.com/frhagn/Typewriter/blob/d29cbade9b6be4d29b8e4b83764a9eb82a41064f/src/ItemTemplates/Models/Models.tst

$rootnamespace$ for example doesnt get rendered to anything 

$IsEnumerable doesnt either: 
public $name: $Type = $IsEnumerable[[]][$Default];]

could you please provide a small example?

**Comment by FreeFrags** [comment]
I think i get it, when im done ill post a template we can use as a default maybe?

**Comment by frhagn** [comment]
It's an old template from a previous version that isn't published anymore, I've just forgotten to remove it  from the source.. I'vd decided to publish template examples on the [Typewriter web site](http://frhagn.github.io/Typewriter/pages/examples.html) instead of adding item templates to the extension itself since it's easier to keep everyting up-to-date this way. 

`$rootnamespace$` isn't a Typewriter property, it's a Visual Studio Item Template property that gets replaced when you add the item to a project.

Anyway, if you have a good template example it's definitely a welcome addition to the web site.

**Comment by FreeFrags** [comment]
Thanks for the explaination ill keep you updated

**Comment by FreeFrags** [comment]
how would you get the value of the following 
```c#
public string myString = "test"
```
Until now i got this far which would set the default for the type. but this example has a value assigend how do i check if it has one and if so set that one instead of the default?

```typescript
 $Properties[
        public $name: $Type = $Default;
  ]
```

**Comment by frhagn** [comment]
I'm afraid there's no support for reading values assigned to fields.
